//! Guandan websocket protocol backed by the shared room storage.

use std::{
    collections::HashMap,
    fmt,
    sync::Mutex,
};

use axum::extract::ws::{Message, WebSocket};
use futures::{SinkExt, StreamExt};
use rand::seq::SliceRandom;
use rand::thread_rng;
use serde::{Deserialize, Serialize};
use shengji_core::guandan::{
    compare::beats_at_level,
    deck::{build_deck, deal, CARDS_PER_PLAYER},
    strength::strength_basic,
    team::{
        four_player_ace_win, four_player_promotion_steps, team_for_seat, Team, TeamLevels,
    },
    tribute::{can_resist_tribute, four_player_tribute_plan, TributePlan},
    CardFace, Rank, TableConfig, MAX_PLAYERS, MIN_PLAYERS,
};
use storage::{HashMapStorage, Storage};
use tokio::sync::mpsc;

use crate::guandan_serving_types::{
    GuandanGameState, GuandanStorageMessage, GuandanTablePlay, VersionedGuandanGame,
};

lazy_static::lazy_static! {
    static ref GUANDAN_OBSERVERS: Mutex<HashMap<Vec<u8>, Vec<String>>> = Mutex::new(HashMap::new());
}

#[derive(Clone, Debug, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum GuandanClientMessage { Join { room: String, name: String }, ReorderPlayers { order: [usize; 2] }, SetParticipation { active: bool }, Start { player_count: usize }, Play { card_indexes: Vec<usize> }, TributeCard { card_index: usize }, ReturnTribute { card_index: usize }, Pass, EndRound }

#[derive(Clone, Debug, Serialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum GuandanServerMessage { Connected { protocol: &'static str }, Joined { room: String, seat: usize }, Waiting { players: Vec<String>, observers: Vec<String>, minimum_players: usize, maximum_players: usize }, Started { player_count: usize, cards_per_player: usize }, Hand { cards: Vec<CardFace> }, State { players: Vec<String>, observers: Vec<String>, turn: usize, hand_counts: Vec<usize>, last_play: Vec<CardFace>, last_player: Option<usize>, table_plays: Vec<GuandanTablePlay>, passes: usize, trick_complete: bool, level: Rank, team_levels: TeamLevels, finish_order: Vec<usize>, last_game_winner: Option<usize>, last_game_winner_team: Option<Team>, last_promotion_steps: Option<usize>, pending_tribute: Option<TributePlan>, tribute_resisted: bool, match_winner: Option<Team> }, Error { message: String } }

#[derive(Debug)] enum PlayError { Storage, Invalid(&'static str) }
impl From<()> for PlayError { fn from(_: ()) -> Self { Self::Storage } }
impl fmt::Display for PlayError { fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result { match self { Self::Storage => write!(f, "temporary room storage error"), Self::Invalid(message) => write!(f, "{message}") } } }

pub fn validate_start(player_count: usize) -> Result<TableConfig, &'static str> { let table=TableConfig::new(player_count)?; if !table.is_even_table(){return Err("Guandan supports even tables: 4, 6, 8, 10, 12, 14");} Ok(table) }
fn encode(message:&GuandanServerMessage)->Option<String>{serde_json::to_string(message).ok()}
fn send(tx:&mpsc::UnboundedSender<String>,message:&GuandanServerMessage){if let Some(text)=encode(message){let _=tx.send(text);}}
fn observers_for(key:&[u8])->Vec<String>{GUANDAN_OBSERVERS.lock().ok().and_then(|o|o.get(key).cloned()).unwrap_or_default()}
fn is_observer(key:&[u8],name:&str)->bool{observers_for(key).iter().any(|o|o==name)}
async fn current_seat(storage:&HashMapStorage<VersionedGuandanGame>,key:&[u8],name:&str)->Option<usize>{storage.clone().get(key.to_vec()).await.ok()?.game.player_names.iter().position(|n|n==name)}
fn waiting_message(key:&[u8],game:&GuandanGameState)->GuandanServerMessage{GuandanServerMessage::Waiting{players:game.player_names.clone(),observers:observers_for(key),minimum_players:MIN_PLAYERS,maximum_players:MAX_PLAYERS}}
fn state_message(key:&[u8],game:&GuandanGameState)->GuandanServerMessage{GuandanServerMessage::State{players:game.player_names.clone(),observers:observers_for(key),turn:game.turn,hand_counts:game.hand_counts(),last_play:game.last_play.clone(),last_player:game.last_player,table_plays:game.table_plays.clone(),passes:game.passes,trick_complete:game.trick_complete,level:game.level,team_levels:game.team_levels,finish_order:game.finish_order.clone(),last_game_winner:game.last_game_winner,last_game_winner_team:game.last_game_winner_team,last_promotion_steps:game.last_promotion_steps,pending_tribute:game.pending_tribute.clone(),tribute_resisted:game.tribute_resisted,match_winner:game.match_winner}}
fn advance_turn(game:&mut GuandanGameState){if game.hands.is_empty(){return;}for _ in 0..game.hands.len(){game.turn=(game.turn+1)%game.hands.len();if !game.hands[game.turn].is_empty(){break;}}}

fn settle_and_redeal_if_complete(game:&mut GuandanGameState)->Result<bool,&'static str>{
 let active_players=game.hands.iter().filter(|h|!h.is_empty()).count(); if active_players>1||game.finish_order.is_empty(){return Ok(false)}
 let player_count=game.hands.len(); let table=validate_start(player_count)?; let previous_finish_order=game.finish_order.clone(); let winner=previous_finish_order[0]; let winner_team=team_for_seat(table,winner)?; let winner_level=game.team_levels.level_for(winner_team);
 game.last_game_winner=Some(winner); game.last_game_winner_team=Some(winner_team);
 let promotion_steps=if player_count==4{four_player_promotion_steps(table,&previous_finish_order)?}else{1}; game.last_promotion_steps=Some(promotion_steps);
 if winner_level==Rank::Ace{let wins_match=if player_count==4{four_player_ace_win(table,&previous_finish_order)?}else{true};if wins_match{game.match_winner=Some(winner_team);game.trick_complete=true;return Ok(true)}}
 let next_level=if winner_level==Rank::Ace{Rank::Ace}else{game.team_levels.advance_winner_by(winner_team,promotion_steps)};
 let mut deck=build_deck(table);deck.shuffle(&mut thread_rng());let(hands,remainder)=deal(table,&deck)?;if !remainder.is_empty(){return Err("next Guandan deal left undealt cards")}
 game.hands=hands;game.turn=winner;game.level=next_level;game.finish_order.clear();game.last_play.clear();game.last_player=None;game.table_plays.clear();game.passes=0;game.trick_complete=false;game.pending_tribute=None;game.tribute_cards.clear();game.return_cards.clear();game.tribute_resisted=false;
 if player_count==4{let plan=four_player_tribute_plan(table,&previous_finish_order)?;if can_resist_tribute(&plan,&game.hands){game.tribute_resisted=true}else{game.pending_tribute=Some(plan)}} Ok(true)
}
fn validate_play_against_table(cards:&[CardFace],current:&[CardFace],level:Rank)->Result<(),&'static str>{let candidate=strength_basic(cards).ok_or("selected cards are not a legal Guandan pattern")?;if current.is_empty(){return Ok(())}let table=strength_basic(current).ok_or("current table play is invalid")?;if beats_at_level(candidate,table,level){Ok(())}else{Err("play must beat the current table play")}}

pub async fn websocket(socket:WebSocket,storage:HashMapStorage<VersionedGuandanGame>,subscriber_id:usize){
 let(mut ws_tx,mut ws_rx)=socket.split();let(tx,mut rx)=mpsc::unbounded_channel::<String>();let writer=tokio::spawn(async move{while let Some(text)=rx.recv().await{if ws_tx.send(Message::Text(text)).await.is_err(){break;}}});send(&tx,&GuandanServerMessage::Connected{protocol:"guandan-v20-player-observers"});let mut joined_room:Option<Vec<u8>>=None;let mut joined_name:Option<String>=None;let mut subscription_task=None;
 while let Some(result)=ws_rx.next().await{let message=match result{Ok(m)=>m,Err(_)=>break};let text=match message{Message::Text(t)=>t,Message::Binary(b)=>match String::from_utf8(b){Ok(t)=>t,Err(_)=>continue},Message::Close(_)=>break,Message::Ping(_)|Message::Pong(_)=>continue};let command=match serde_json::from_str::<GuandanClientMessage>(&text){Ok(c)=>c,Err(_)=>{send(&tx,&GuandanServerMessage::Error{message:"invalid guandan command".into()});continue}};
 match command{
 GuandanClientMessage::Join{room,name}=>{if joined_room.is_some(){send(&tx,&GuandanServerMessage::Error{message:"already joined a guandan room".into()});continue}let key=room.as_bytes().to_vec();if is_observer(&key,&name){send(&tx,&GuandanServerMessage::Error{message:"name is already in use".into()});continue}let n=name.clone();let r=storage.clone().execute_operation_with_messages(key.clone(),move|mut s|{if s.game.started||s.game.player_names.len()>=MAX_PLAYERS||s.game.player_names.iter().any(|x|x==&n){return Err(())}s.game.player_names.push(n);s.bump_version();Ok((s,vec![GuandanStorageMessage::StateChanged]))}).await;let seat=match r{Ok(_)=>match current_seat(&storage,&key,&name).await{Some(s)=>s,None=>continue},Err(_)=>{send(&tx,&GuandanServerMessage::Error{message:"room is full, game already started, or name is already in use".into()});continue}};joined_room=Some(key.clone());joined_name=Some(name.clone());send(&tx,&GuandanServerMessage::Joined{room,seat});if let Ok(s)=storage.clone().get(key.clone()).await{send(&tx,&waiting_message(&key,&s.game))}let mut sub=match storage.clone().subscribe(key.clone(),subscriber_id).await{Ok(s)=>s,Err(_)=>continue};let txs=tx.clone();let ss=storage.clone();let ns=name;subscription_task=Some(tokio::spawn(async move{while sub.recv().await.is_some(){if let Ok(s)=ss.clone().get(key.clone()).await{let seat=s.game.player_names.iter().position(|x|x==&ns);if s.game.started{send(&txs,&state_message(&key,&s.game));if let Some(seat)=seat{if let Some(hand)=s.game.private_hand(seat){send(&txs,&GuandanServerMessage::Hand{cards:hand.to_vec()})}}}else{send(&txs,&waiting_message(&key,&s.game))}}}}));}
 GuandanClientMessage::SetParticipation{active}=>{let(key,name)=match(joined_room.clone(),joined_name.clone()){(Some(k),Some(n))=>(k,n),_=>continue};let k2=key.clone();let n2=name.clone();let r=storage.clone().execute_operation_with_messages(key,move|mut s|{if s.game.started{return Err(())}let mut obs=GUANDAN_OBSERVERS.lock().map_err(|_|())?;let ro=obs.entry(k2).or_default();if active{if s.game.player_names.iter().any(|n|n==&n2){return Ok((s,vec![]))}let i=ro.iter().position(|n|n==&n2).ok_or(())?;if s.game.player_names.len()>=MAX_PLAYERS{return Err(())}ro.remove(i);s.game.player_names.push(n2)}else{let i=s.game.player_names.iter().position(|n|n==&n2).ok_or(())?;let removed=s.game.player_names.remove(i);if !ro.iter().any(|n|n==&removed){ro.push(removed)}}s.bump_version();Ok((s,vec![GuandanStorageMessage::StateChanged]))}).await;if r.is_err(){send(&tx,&GuandanServerMessage::Error{message:"participation can only be changed before the game starts".into()})}}
 GuandanClientMessage::ReorderPlayers{order}=>{let(key,name)=match(joined_room.clone(),joined_name.clone()){(Some(k),Some(n))=>(k,n),_=>continue};let r=storage.clone().execute_operation_with_messages(key,move|mut s|{let len=s.game.player_names.len();if s.game.started||order[0]>=len||order[1]>=len||order[0].abs_diff(order[1])!=1{return Err(())}let cur=s.game.player_names.iter().position(|n|n==&name).ok_or(())?;if cur!=order[0]&&cur!=order[1]{return Err(())}s.game.player_names.swap(order[0],order[1]);s.bump_version();Ok((s,vec![GuandanStorageMessage::StateChanged]))}).await;if r.is_err(){send(&tx,&GuandanServerMessage::Error{message:"players can only swap with an adjacent seat before the game starts".into()})}}
 GuandanClientMessage::Start{player_count}=>{let(key,name)=match(joined_room.clone(),joined_name.clone()){(Some(k),Some(n))=>(k,n),_=>continue};let seat=match current_seat(&storage,&key,&name).await{Some(s)=>s,None=>{send(&tx,&GuandanServerMessage::Error{message:"observers cannot start the game".into()});continue}};if seat!=0{send(&tx,&GuandanServerMessage::Error{message:"only seat 1 can start the game".into()});continue}let table=match validate_start(player_count){Ok(t)=>t,Err(m)=>{send(&tx,&GuandanServerMessage::Error{message:m.into()});continue}};let r=storage.clone().execute_operation_with_messages(key.clone(),move|mut s|{if s.game.player_names.len()!=table.player_count{return Err(())}let mut deck=build_deck(table);deck.shuffle(&mut thread_rng());let(hands,rem)=deal(table,&deck).map_err(|_|())?;if !rem.is_empty(){return Err(())}s.game.started=true;s.game.hands=hands;s.game.turn=0;s.game.last_play.clear();s.game.last_player=None;s.game.table_plays.clear();s.game.passes=0;s.game.trick_complete=false;s.game.finish_order.clear();s.game.last_game_winner=None;s.game.last_game_winner_team=None;s.game.last_promotion_steps=None;s.game.pending_tribute=None;s.game.tribute_cards.clear();s.game.return_cards.clear();s.game.tribute_resisted=false;s.game.match_winner=None;s.bump_version();Ok((s,vec![GuandanStorageMessage::StateChanged]))}).await;if r.is_err(){send(&tx,&GuandanServerMessage::Error{message:"selected player count must match active players".into()});continue}if let Ok(s)=storage.clone().get(key.clone()).await{send(&tx,&GuandanServerMessage::Started{player_count,cards_per_player:CARDS_PER_PLAYER});send(&tx,&state_message(&key,&s.game));if let Some(hand)=s.game.private_hand(seat){send(&tx,&GuandanServerMessage::Hand{cards:hand.to_vec()})}}}
 GuandanClientMessage::Play{mut card_indexes}=>{let(key,name)=match(joined_room.clone(),joined_name.clone()){(Some(k),Some(n))=>(k,n),_=>continue};let seat=match current_seat(&storage,&key,&name).await{Some(s)=>s,None=>continue};card_indexes.sort_unstable();card_indexes.dedup();let indexes=card_indexes;let r:Result<u64,PlayError>=storage.clone().execute_operation_with_messages(key,move|mut s|{if s.game.normal_play_blocked(){return Err(PlayError::Invalid("normal play is blocked until tribute is resolved"))}if !s.game.started||s.game.trick_complete||s.game.turn!=seat||indexes.is_empty()||indexes.last().copied().unwrap_or(0)>=s.game.hands[seat].len(){return Err(PlayError::Invalid("not your turn or invalid card selection"))}let cards=indexes.iter().map(|&i|s.game.hands[seat][i]).collect::<Vec<_>>();validate_play_against_table(&cards,&s.game.last_play,s.game.level).map_err(PlayError::Invalid)?;for &i in indexes.iter().rev(){s.game.hands[seat].remove(i);}s.game.last_play=cards.clone();s.game.last_player=Some(seat);s.game.table_plays.push(GuandanTablePlay{player:seat,cards});s.game.passes=0;if s.game.hands[seat].is_empty()&&!s.game.finish_order.contains(&seat){s.game.finish_order.push(seat)}let settled=settle_and_redeal_if_complete(&mut s.game).map_err(PlayError::Invalid)?;if !settled{advance_turn(&mut s.game)}s.bump_version();Ok((s,vec![GuandanStorageMessage::StateChanged]))}).await;if let Err(e)=r{send(&tx,&GuandanServerMessage::Error{message:e.to_string()})}}
 GuandanClientMessage::TributeCard{card_index}=>{let(key,name)=match(joined_room.clone(),joined_name.clone()){(Some(k),Some(n))=>(k,n),_=>continue};let seat=match current_seat(&storage,&key,&name).await{Some(s)=>s,None=>continue};let r:Result<u64,PlayError>=storage.clone().execute_operation_with_messages(key,move|mut s|{if !s.game.started||s.game.match_winner.is_some(){return Err(PlayError::Invalid("tribute is not available now"))}s.game.submit_tribute_card(seat,card_index).map_err(PlayError::Invalid)?;s.bump_version();Ok((s,vec![GuandanStorageMessage::StateChanged]))}).await;if let Err(e)=r{send(&tx,&GuandanServerMessage::Error{message:e.to_string()})}}
 GuandanClientMessage::ReturnTribute{card_index}=>{let(key,name)=match(joined_room.clone(),joined_name.clone()){(Some(k),Some(n))=>(k,n),_=>continue};let seat=match current_seat(&storage,&key,&name).await{Some(s)=>s,None=>continue};let r:Result<u64,PlayError>=storage.clone().execute_operation_with_messages(key,move|mut s|{if !s.game.started||s.game.match_winner.is_some(){return Err(PlayError::Invalid("return tribute is not available now"))}s.game.submit_return_card(seat,card_index).map_err(PlayError::Invalid)?;if s.game.tribute_exchange_complete(){s.game.finalize_tribute_exchange().map_err(PlayError::Invalid)?}s.bump_version();Ok((s,vec![GuandanStorageMessage::StateChanged]))}).await;if let Err(e)=r{send(&tx,&GuandanServerMessage::Error{message:e.to_string()})}}
 GuandanClientMessage::Pass=>{let(key,name)=match(joined_room.clone(),joined_name.clone()){(Some(k),Some(n))=>(k,n),_=>continue};let seat=match current_seat(&storage,&key,&name).await{Some(s)=>s,None=>continue};let r=storage.clone().execute_operation_with_messages(key,move|mut s|{if s.game.normal_play_blocked()||!s.game.started||s.game.trick_complete||s.game.turn!=seat||s.game.last_player.is_none(){return Err(())}s.game.passes+=1;let active=s.game.hands.iter().filter(|h|!h.is_empty()).count();if s.game.passes+1>=active{s.game.turn=s.game.last_player.unwrap_or(s.game.turn);s.game.trick_complete=true}else{advance_turn(&mut s.game)}s.bump_version();Ok((s,vec![GuandanStorageMessage::StateChanged]))}).await;if r.is_err(){send(&tx,&GuandanServerMessage::Error{message:"cannot pass now".into()})}}
 GuandanClientMessage::EndRound=>{let key=match joined_room.clone(){Some(k)=>k,None=>continue};let r=storage.clone().execute_operation_with_messages(key,move|mut s|{if s.game.normal_play_blocked()||!s.game.started||!s.game.trick_complete{return Err(())}let winner=s.game.last_player.ok_or(())?;s.game.turn=winner;if s.game.hands[winner].is_empty(){advance_turn(&mut s.game)}s.game.last_play.clear();s.game.last_player=None;s.game.table_plays.clear();s.game.passes=0;s.game.trick_complete=false;s.bump_version();Ok((s,vec![GuandanStorageMessage::StateChanged]))}).await;if r.is_err(){send(&tx,&GuandanServerMessage::Error{message:"round is not ready to end".into()})}}
 }}if let Some(key)=joined_room{storage.unsubscribe(key,subscriber_id).await}if let Some(task)=subscription_task{task.abort()}writer.abort();
}

#[cfg(test)] mod tests{
 use super::*;use shengji_core::guandan::Suit;fn card(suit:Suit,rank:Rank)->CardFace{CardFace::Suited{suit,rank}}
 #[test]fn accepts_even_test_tables(){for count in[4usize,6,8,10,12,14]{assert_eq!(validate_start(count).unwrap().player_count,count)}}
 #[test]fn seat_reorder_command_deserializes(){let c:GuandanClientMessage=serde_json::from_str(r#"{"type":"reorder_players","order":[0,1]}"#).unwrap();assert!(matches!(c,GuandanClientMessage::ReorderPlayers{order:[0,1]}))}
 #[test]fn participation_command_deserializes(){let c:GuandanClientMessage=serde_json::from_str(r#"{"type":"set_participation","active":false}"#).unwrap();assert!(matches!(c,GuandanClientMessage::SetParticipation{active:false}))}
 #[test]fn tribute_commands_deserialize(){let t:GuandanClientMessage=serde_json::from_str(r#"{"type":"tribute_card","card_index":3}"#).unwrap();assert!(matches!(t,GuandanClientMessage::TributeCard{card_index:3}));let r:GuandanClientMessage=serde_json::from_str(r#"{"type":"return_tribute","card_index":2}"#).unwrap();assert!(matches!(r,GuandanClientMessage::ReturnTribute{card_index:2}))}
 #[test]fn state_message_exposes_observers_tribute_and_promotion(){let key=b"test-room";if let Ok(mut o)=GUANDAN_OBSERVERS.lock(){o.insert(key.to_vec(),vec!["Watcher".into()]);}let mut g=GuandanGameState::default();g.pending_tribute=Some(TributePlan::Single{giver:3,receiver:0});g.last_promotion_steps=Some(1);let j=encode(&state_message(key,&g)).unwrap();assert!(j.contains("observers")&&j.contains("Watcher")&&j.contains("pending_tribute")&&j.contains("last_promotion_steps"));}
 fn finished_game(order:Vec<usize>)->GuandanGameState{let mut g=GuandanGameState::default();g.started=true;g.player_names=vec!["A1".into(),"B1".into(),"A2".into(),"B2".into()];g.hands=vec![vec![],vec![],vec![],vec![card(Suit::Clubs,Rank::Two)]];g.finish_order=order;g}
 #[test]fn one_two_finish_advances_and_activates_double_tribute(){let mut g=finished_game(vec![0,2,1]);assert!(settle_and_redeal_if_complete(&mut g).unwrap());assert_eq!(g.team_levels.team_a,Rank::Five);assert_eq!(g.last_promotion_steps,Some(3));assert!(g.pending_tribute.is_some()||g.tribute_resisted);assert!(g.hands.iter().all(|h|h.len()==CARDS_PER_PLAYER));}
 #[test]fn one_three_finish_activates_single_tribute(){let mut g=finished_game(vec![0,1,2]);assert!(settle_and_redeal_if_complete(&mut g).unwrap());assert_eq!(g.team_levels.team_a,Rank::Four);assert_eq!(g.last_promotion_steps,Some(2));assert!(g.pending_tribute.is_some()||g.tribute_resisted);}
 #[test]fn one_four_finish_advances_one_level(){let mut g=finished_game(vec![0,1,3]);assert!(settle_and_redeal_if_complete(&mut g).unwrap());assert_eq!(g.team_levels.team_a,Rank::Three);assert_eq!(g.last_promotion_steps,Some(1));assert_eq!(g.level,Rank::Three);assert!(g.pending_tribute.is_some()||g.tribute_resisted);assert!(g.hands.iter().all(|h|h.len()==CARDS_PER_PLAYER));}
 #[test]fn current_level_single_beats_ace(){assert!(validate_play_against_table(&[card(Suit::Spades,Rank::Five)],&[card(Suit::Clubs,Rank::Ace)],Rank::Five).is_ok())}
}
